api/Event/index.ts
common/DropBox/index.tsx
common/DropDown/index.tsx
common/DropDown/styles.ts
common/Modal/FineBookModal/index.tsx
common/Modal/TwoButtonModal/index.tsx
index.html
pages/FineBook/components/DetailFine/components/CircleButtonList/index.tsx
pages/FineBook/components/DetailFine/components/CircleButtonList/styles.ts
pages/FineBook/components/DetailFine/components/CircleDropButton/index.tsx
pages/FineBook/components/DetailFine/components/DateController/index.tsx
pages/FineBook/components/DetailFine/components/DateController/styles.ts
pages/FineBook/components/DetailFine/components/DetailList/index.tsx
pages/FineBook/components/DetailFine/components/DetailsHeader/index.tsx
pages/FineBook/components/DetailFine/components/DetailsHeader/styles.ts
pages/FineBook/components/DetailFine/components/DropDownWrapper/index.tsx
pages/FineBook/components/DetailFine/components/Pagination/index.tsx
pages/FineBook/components/DetailFine/components/Pagination/styles.ts
pages/FineBook/components/DetailFine/components/TableHead/index.tsx
pages/FineBook/components/DetailFine/components/TableHead/styles.ts
pages/FineBook/components/DetailFine/components/UserDetails/index.tsx
pages/FineBook/components/DetailFine/index.tsx
pages/FineBook/utils/dateFilterToQuery.ts
pages/Home/components/CardList/index.tsx
queries/Detail/useGetDetailList.ts
styles/Theme.ts
types/event.d.ts
types/global.d.ts
utils/getStatusIcon.ts
utils/pushDataLayer.ts

- pushDataLayer() 추가
- gtm 셋팅
- filter 기능 추가

Feature: filter관련 로직 추가 및 gtm, dataLayer 추가

---

api/User/index.ts
assets/icons/System/index.tsx
common/Modal/UserConfigModal/index.tsx
constants/Withdrawal.ts
pages/WholeCalendar/index.tsx
pages/Withdrawal/components/Confirm/index.tsx
pages/Withdrawal/components/Reason/index.tsx
queries/Auth/useUserWithdrawalMutation.ts

- 그룹 레이아웃 회원탈퇴 기능 연결
- 회원 탈퇴 시 메인페이지로 이동하며, 그룹리스트 데이터 삭제

Feat/회원 탈퇴 기능 추가

---

common/Calendar/DateCellWithMark/index.tsx
common/Calendar/DateCellWithTag/index.tsx
common/Calendar/index.tsx
pages/WholeCalendar/index.tsx

- api 수정되어 상태값 변경
- 현재 달이 아닌 곳에도 상태값 나타나는 에러 수정
- 0 이 출력되는 에러 수정

[feat] 월별 납부 상태 수정

---

api/Group/index.ts
common/Modal/GroupSettingModal/AdminModal/index.tsx
queries/Group/useGroupList.ts
queries/Group/useUpdateGroup.ts

- 무한스크롤 페이지 에러 수정
- 닉네임 변경 api, 그룹 변경 api 수정

[Fix] 무한스크롤 에러 수정, 닉네임 변경, 그룹 변경 api 수정

---

api/Auth/index.ts
common/DropBox/index.tsx
common/DropDown/index.tsx
common/Modal/FineBookModal/index.tsx
layouts/Group/components/Header/index.tsx
pages/FineBook/components/DetailFine/components/DateController/index.tsx
pages/FineBook/components/DetailFine/components/TableHead/index.tsx
pages/FineBook/components/DetailFine/components/TableHead/styles.ts
pages/FineBook/components/DetailFine/components/UserDetails/index.tsx
pages/FineBook/components/DetailFine/index.tsx
pages/MemberManagement/components/MemberListItem/index.tsx

- 드롭 다운 외부 클릭시 닫히게끔 설정
- 드롭 다운 아이템 선택시 안닫히는 문제 해결
- 드롭 다운 트리거 재 클릭시 다시 열리는 문제 해결

[feat] 드롭 다운 수정

---

common/Calendar/DateCellWithTag/styles.ts
common/Calendar/styles.ts
pages/FineBook/components/DetailFine/index.tsx

[fix] 태그 달력 레이아웃 깨지는 에러 수정

---

common/Button/index.tsx
common/Calendar/index.tsx
common/DropBox/index.tsx
common/DropDown/index.tsx
common/Modal/ChangAdminModal/index.tsx
common/Modal/CreateGroupModal/index.tsx
common/Modal/FineBookModal/index.tsx
common/Modal/GroupSettingModal/AdminModal/index.tsx
common/Modal/TwoButtonModal/index.tsx
layouts/Group/components/GroupList/index.tsx
layouts/Group/components/SideBar/index.tsx
pages/FineBook/components/DetailFine/components/CircleButtonList/index.tsx
pages/FineBook/components/DetailFine/components/CircleDropButton/index.tsx
pages/FineBook/components/DetailFine/components/DateController/index.tsx
pages/FineBook/components/DetailFine/components/DetailList/index.tsx
pages/FineBook/components/DetailFine/components/DropDownWrapper/index.tsx
pages/FineBook/components/DetailFine/components/InviteModal/index.tsx
pages/FineBook/components/DetailFine/components/TableHead/index.tsx
pages/FineBook/components/DetailFine/components/UserDetails/index.tsx
pages/FineBook/components/DetailFine/components/UserDetails/styles.ts
pages/FineBook/components/DetailFine/index.tsx
pages/FineBook/utils/dateFilter.ts
pages/Home/components/Card/AddCard/index.tsx
pages/Home/components/Card/AddCard/styles.ts
pages/Home/components/CardList/index.tsx
pages/Home/components/Header/index.tsx
pages/MemberManagement/components/MemberListItem/index.tsx
pages/MemberManagement/index.tsx
utils/customedWeek.ts

[피그마 바로가기](https://www.figma.com/file/FRRGkDv1hGZm2U7ajFxHY3/%ED%99%94%EB%A9%B4%EB%94%94%EC%9E%90%EC%9D%B8?node-id=1015-53158&t=huCMc1GbsMeBcOd0-0)
[노션 바로가기](https://www.notion.so/GTM-GA4-409030309f724dabba57ac5eb28c27dd?pvs=4)

feature: gtm id 셋팅 완료

---

.github/workflows/staging-aws-deploy.yml
.gitignore
package.json
webpack.config.ts

추가적인 개발 서버 배포를 위한 yml 파일 추가 및 github actions 설정
<br />
- webpack 수정
- .env.staging추가
- yml파일 추가
- build:staging명령어 추가
<br />
-

chore: staging서버 설정

---

src/api/Event/index.ts
src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx
src/components/DetailFine/DateController/index.tsx
src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/Pagination/index.tsx
src/components/DetailFine/TableHead/index.tsx
src/pages/FineBook/DetailFine/index.tsx
src/pages/WholeCalendar/index.tsx
src/queries/Detail/useGetDetailList.ts
src/utils/dateFilterToQuery.ts
src/utils/detailFilterToQuery.ts
src/utils/tests/dateFilter.test.ts

DetailFine 에러 수정 
- DetailList 클릭 시 에러 수정
- DetailList 필터링 에러 수정(hooks rule)
- 오늘 버튼 미작동 이슈 해결
- 각종 네이밍 변경
<br />
- hooks rule 관련은 조건부 렌더링 관련 찾아보시면 됩니다

DetailFine 에러 수정 네이밍 변경

---

.github/workflows/aws-deploy.yml
.github/workflows/staging-aws-deploy.yml
src/api/index.ts

개발 서버 추가로 github actions workflow 업데이트
<br />
- api base url 변경
- workflow 수정
<br />

docs: 개발 서버 추가로 github actions workflow 업데이트

---

src/components/@common/Modal/FineBookModal/FineBookUpdateModal/index.tsx

Fix: FineBookUpdate 오류 수정
<br />
- api response 변경에 따라서  onSuccessUpdateDetail -> success 내부 변경

Fix: FineBookUpdate 오류 수정

---

src/components/DetailFine/DateController/index.tsx
src/components/DetailFine/DateController/styles.ts

- 주간 필터링 arrow icon 추가
- 필터링 위치 변경
<br />
- 주간 필터링 arrow icon 추가
- 필터링 위치 변경
<br />
-

Style: 필터링 버튼 스타일 변경

---

src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
src/components/DetailFine/UserDetails/index.tsx
src/queries/Detail/useGetDetailList.ts
src/store/detailFilter.ts

- dataLayer 코드 추가
<br />
- 코드와 상관 없는 gtm dataLayer 수정 부분입니다
<br />
- https://www.notion.so/49ad1ecf9f2d43479126d9d63383d64b?pvs=4

feat: gtm dataLayer 코드 추가

---

src/components/@common/Modal/FineBookModal/reducer/selectedDataReducer.ts
src/components/@common/Modal/GroupSettingModal/UserModal/index.tsx
src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/DetailList/styles.ts
src/components/DetailFine/UserDetails/index.tsx
src/utils/convertPriceFormat.ts
src/utils/customedWeek.ts

오픈베타 에러 수정
<br />
- UserModal nickname 15자 제한
- memo에 내용 없을 시 detaillist에 사유와 메모 구분점 제거
- 오타 수정
- 주간 필터링 텍스트 '임시' 대응 (1주,2주,3주 ~~)
- 금액 100만원 이상 추가 입력 제한 추가
<br />
- 주간 필터링 관련해서는 다른 구조를 생각해보는 것도 좋을 것 같습니다!

오픈베타 에러 수정

---

src/components/@common/GroupColorList/index.tsx
src/components/@common/GroupColorList/styles.ts
src/components/@common/Label/index.tsx
src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
src/components/DetailFine/DateController/hook/useDateController.ts
src/components/DetailFine/UserDetails/index.tsx
src/utils/customedWeek.ts

오픈 베타 오류 수정
<br />
- 라벨을 클릭하면 선택한 color가 기본으로 돌아오는 현상
- 이벤트 버블링 때문인 거 같기는 한데,, 정확히 이유를 모르겠습니다 😢 알려주세요..
- 주간 필터링 시 날짜가 NaN으로 출력
- 1주, 2주 -> 첫째 주, 둘째 주로 변경되면서 기존에 사용하던 로직이 적용 안 됨 
- [0f4ad96](https://github.com/so-sim/front/pull/139/commits/0f4ad96ec3daddd738c71a0af27f97d1737ea12a)
- obj -> array로 변경해봤는데 어떤가요 !? 🧐
- 메모 placeholder 수정
<br />
-

Fix : 오픈 베타 오류 수정

---

src/api/User/index.ts
src/components/Withdrawal/Reason/index.tsx
src/layouts/Group/components/SideBar/index.tsx
src/layouts/Group/components/SideBar/styles.ts
src/types/user.d.ts

회원 탈퇴 api 메서드 수정
- 회원 탈퇴 api 메서드 수정
<br />
-

Fix: 회원 탈퇴 api 메서드 수정

---

src/components/@common/DropBox/CalendarDropBox/index.tsx
src/components/@common/DropBox/styles.ts
src/components/DetailFine/DateController/styles.ts
src/components/DetailFine/UserDetails/index.tsx
src/layouts/Group/components/SideBar/styles.ts

오픈 베타 핫픽스 수정
<br />
- 드롭다운 font 미적용 이슈 해결(width 이후로 미적용되는 방법 알아봐야함)
- 드롭다운 style 중앙정렬 적용
- 내역 추가하기 - 날짜 여백 클릭오류 수정 (전체 div에 click이벤트 적용, modal은 버블링제어)

오픈 베타 핫픽스 수정

---

src/components/@common/Calendar/DateCellWithTag/index.tsx
src/components/@common/Modal/FineBookModal/FormFileds/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
src/components/DetailFine/DropDownWrapper/CircleDropButton/test/CircleDropButton.test.tsx
src/components/DetailFine/DropDownWrapper/index.tsx
src/components/DetailFine/UserDetails/index.tsx
src/hooks/useSituationList.ts
src/queries/Auth/useUserWithdrawalMutation.ts

button naming 수정
<br />
- button naming 수정
<br />
-

Hotfix: button naming 수정

---

src/components/DetailFine/UserDetails/index.tsx

button Text 변경 (situation)
<br />
-  button Text 변경 (situation)
<br />
-

fix: button Text 변경 (situation)

---

src/assets/icons/System/Search.svg
src/assets/icons/System/index.tsx
src/components/DetailFine/FilterController/AutoComplete/index.tsx
src/components/DetailFine/FilterController/AutoComplete/styles.ts

팀원검색>키보드 조작할 수 있도록 기능 추가 #155 
<br />
- 박재민에 포커스된 상태
- 조작키
- 상,하 방향키: 포커스 이동
- enter: 포커스된 유저 검색
- esc: 검색창에 입력된 유저 제거 
<br />
-

Feat: 팀원검색>키보드 조작할 수 있도록 기능 추가

---

src/App.tsx
src/assets/icons/Logo/index.tsx
src/assets/icons/System/Menu.svg
src/assets/icons/System/index.tsx
src/components/@common/Modal/styles.ts
src/components/Home/Card/AddCard/index.tsx
src/components/Home/Card/GroupCard/index.tsx
src/components/Home/Card/GroupCard/styles.ts
src/components/Home/Card/index.tsx
src/components/Home/Card/styles.ts
src/components/Home/CardList/index.tsx
src/components/Home/CardList/styles.ts
src/components/Home/Header/index.tsx
src/constants/ServiceLink.ts
src/hooks/Group/useInfinityGroupList.ts
src/layouts/Mobile/components/MobileHeader/index.tsx
src/layouts/Mobile/components/MobileHeader/styles.ts
src/layouts/Mobile/components/MobileSideBar/index.tsx
src/layouts/Mobile/components/MobileSideBar/styles.ts
src/layouts/Mobile/index.tsx
src/layouts/Mobile/styles.ts
src/m-components/MobileHome/GroupSection/index.tsx
src/m-components/MobileHome/GroupSection/styles.ts
src/m-pages/MobileCreateGroup/index.tsx
src/m-pages/MobileGroupHome/index.tsx
src/m-pages/MobileHome/index.tsx
src/routes/MobileRouter.tsx
src/types/group.d.ts

모바일 라우터 셋팅 및 모임 홈 완성
<br />
- 모바일 라우터 셋팅
- 모임 만들기 페이지 완성
- 모바일 home 완성
<br />
-

Feat: mobile 라우터 셋팅

---

src/m-pages/MobileMemberManagement/index.tsx
src/m-pages/MobilePreParing/index.tsx

수정된 Mobile Layout 적용
<br />
-  수정된 Mobile Layout 적용
<br />
-

Fix: 수정된 Mobile Layout 적용

---

src/components/@common/Label/index.tsx
src/components/@common/Label/styles.ts
src/components/@common/Modal/InvitationModal/index.tsx
src/components/@common/Modal/InvitationModal/styles.ts
src/pages/Invitation/index.tsx
src/queries/Group/useJoinGroup.ts

초대권 페이지 모바일 추가
<br />
- 초대권 페이지 onSuccess 모바일 라우팅 추가
- 초대권 - 이름설정 모달 Text
https://github.com/so-sim/front/assets/45344418/f7b8c959-886a-4a6d-84d4-513131b363f0
<br />
-

Feat: 초대권 페이지 모바일 추가

---

src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
src/components/DetailFine/DateController/PeriodSettingModal/index.tsx
src/contexts/SelectedFineContext.tsx
src/hooks/Group/useNotificationForm.ts
src/m-components/BottomSheet/FilterBottomSheet/index.tsx
src/pages/FineBook/DetailFine/index.tsx
src/queries/Detail/useGetDetailList.ts
src/queries/Detail/useGetMobileDetailList.ts
src/utils/dateFilter/dayFilter.ts
src/utils/dateFilter/monthFilter.ts
src/utils/dateFilter/weekFilter.ts
src/utils/handleDate.ts

<br />
- Date 포맷 수정 YYYY.MM.DD  --> YYYY-MM-DD
<br />
-

Fix: Date 포맷 수정 YYYY.MM.DD  --> YYYY-MM-DD

---

src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
src/m-components/MobileDetailFine/index.tsx
src/m-components/MobileDetailFine/styles.ts
src/m-pages/MobileCalendar/index.tsx
src/m-pages/MobileCalendar/styles.ts
src/routes/MobileRouter.tsx

<br />
- 내역 리스트 팝업으로 전환 
- 캘린더  Click Event 추가
<br />
-

Feat: 내역 리스트 팝업으로 전환 및 캘린더  Click Event 추가

---

src/components/DetailFine/checkbox.tsx
src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
src/m-components/MobileDetailFine/MobileDetailFineList/styles.ts

<br />
- 내역 리스트 스타일 수정
<br />
-

Feat: 내역 리스트 스타일 수정

---

src/m-components/BottomSheet/styles.ts
src/m-components/MobileDetailFine/index.tsx
src/m-pages/MobileCalendar/styles.ts
src/m-pages/MobileFineBookDetail/index.tsx

fix: z-index수정

---

src/api/Notification/index.ts
src/components/@common/Tooltip/index.tsx
src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts
src/components/Alarm/AlarmDetail/AlarmList/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/styles.ts
src/components/Alarm/AlarmDetail/index.tsx
src/components/Alarm/AlarmDetail/styles.ts
src/components/Alarm/index.tsx
src/components/Alarm/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/layouts/Group/components/SideBar/index.tsx
src/queries/Notification/useGetAlarmList.ts
src/queries/Notification/useGetAlarmListCount.ts
src/queries/Notification/useReadAllNotification.ts
src/queries/Notification/useReadNotification.ts
src/store/alarmInfoState.ts
src/types/notification.d.ts

<br />
- 모바일 버전 추가(컴포넌트 가져다쓰면 될 것 같음)
- 알람 리스트 Hover, 읽음 상태 스타일 수정
- 알람 Info -  List 의 Item(Card)   [hover / disabled / checked] 상태 스타일 추가 필요
<br />
-

Feat: 데스크탑 알람 기능 추가

---

src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/styles.ts
src/components/Alarm/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/styles.ts
src/m-pages/MobileNotificationInfo/index.tsx
src/m-pages/MobileNotificationList/index.tsx
src/routes/MobileRouter.tsx

<br />
모바일은 유지가 저절로 가능함 
but Desktop이 문제
뒤로가기를 제공한다.
or
redux persist인가 비슷한 개념으로 스토리지 사용

Feat: 모바일 Notification 페이지 추가

---

src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
src/components/DetailFine/Toolbar/index.tsx
src/components/DetailFine/Toolbar/styles.ts
src/components/DetailFine/UserDetails/index.tsx
src/constants/Confirm.ts

<br />
- [situation Button 텍스트 포맷 전환](https://github.com/so-sim/front/commit/cdac77c4084ac0b52233d4250297cd9a965b3f89)
- [납부 일괄 변경 페이지 underLine Situation 스타일링](https://github.com/so-sim/front/commit/2c0deaabe8f322ca797172c0ce228bf6553ddba0)
- [Toolbar 팀원 시 워딩 수정](https://github.com/so-sim/front/commit/78e2aaab7aa9e7f85aef98d1c9f5e2ca3b710498)
- [Toolbar zindex 수정](https://github.com/so-sim/front/commit/bf7c3d2b2f151b332d4b74f4bb1bffd82573127d)
- [Confirm Modal 납부여부 수정 시 Text 수정](https://github.com/so-sim/front/commit/c6028339db6b0b1d91983f383f7aee0236569e64)
- [AlarmInfo List 처음 Check 상태가 되도록 수정](https://github.com/so-sim/front/commit/434e3096817136195ed1f9da5f0c2e9acb06665b)
<br />

Fix : QA 내용수정

---

src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts
src/components/Alarm/AlarmDetail/AlarmList/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/styles.ts
src/components/Alarm/styles.ts

<br />
- [fix: 총무가 맞음에도 isAdmin이 false 인 순간이 존재 (의존성배열로 임시 대응)](https://github.com/so-sim/front/commit/e050930e7a4cdd24157fa00c1ca43d92cedf660c)
- [style: 알람 아이콘 스타일 수정](https://github.com/so-sim/front/commit/714da005d8b4eafe2138204c22dc96ca8fcf6cd4)
- [style: 알람 리스트 스타일 수정](https://github.com/so-sim/front/commit/a7e716bf1b565b0e7ef5c601acdbb45636bb9725)
- [feat: 읽을 알람 없을 때 모든 알람 읽기 스타일 수정](https://github.com/so-sim/front/commit/e0aebd77fbf1f29759bd301c843431998907019b)
<br />
-

Fix : QA 수정

---

src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/index.tsx
src/components/Alarm/AlarmDetail/index.tsx
src/components/Alarm/AlarmDetail/styles.ts
src/components/Alarm/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/FilterController/index.tsx
src/constants/Situation.ts
src/hooks/useLockScroll.ts
src/layouts/Group/components/GroupList/index.tsx
src/m-components/BottomSheet/FilterBottomSheet/index.tsx
src/m-components/MobileDetailFine/MobileToolbar/index.tsx
src/m-components/MobileDetailFine/MobileToolbar/styles.ts
src/m-components/MobileDetailFine/index.tsx
src/m-pages/MobileNotificationList/index.tsx
src/pages/FineBook/DetailFine/index.tsx

<br />
- 그룹만들기 성공 시 모달이 안닫히고 초대장 모달과 겹치는 부분 수정
- Mobile ScrollLock으로 인해 스타일이 변형되는 현상 수정
- 모바일 팀원 검색 및 필터링 정상작동되도록 수정
- 간단한 워딩 수정
- Toolbar  팀원 / 총무 일 때 버튼 구성 수정
- Mobile 납부여부 변경 시 redirect 수정
- 알람 클릭 시 해당 내역으로 리다이렉트 
- PC에서 알람클릭 시 해당 알람에 대한 정보로 필터링 해주는 코드 추가
- 각종 버그 수정
- 지금 alarm (notification) 전역상태 관리가 개판입니다...  수정하도록 하겠습니다!!
<br />
-

Fix : QA (알람 클릭 redirect, 필터링 적용, 각종 스타일 수정)

---

src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/styles.ts

style: 읽은 알람 스타일 추가

---

src/components/DetailFine/FilterController/index.tsx
src/components/DetailFine/FilterController/styles.ts

Feat:DetailList 스타일 수정

---

src/layouts/Group/components/GroupList/index.tsx
src/layouts/Group/components/GroupList/styles.ts
src/queries/Group/useGroupList.ts

<br />
- PC / Mobile 그룹 리스트 무한스크롤 되도록 수정
<br />
-

Feat: 그룹 리스트 무한스크롤 적용

---

src/components/DetailFine/DateController/FilterButton/index.tsx
src/components/DetailFine/DateController/index.tsx
src/components/DetailFine/FilterController/index.tsx
src/pages/FineBook/DetailFine/index.tsx

<br />
- 페이지 이동 시 Checkbox 해지되는 오류 수정 
- CheckBox 해지 영역 확장

FIx: 페이지 이동 시 Checkbox 해지되는 오류 수정 및 해지 영역 확장

---

src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/CommonForm/index.tsx
src/hooks/useLockScroll.ts
src/layouts/Mobile/MobileLayout.tsx
src/m-components/MobileDetailFine/index.tsx
src/m-components/MobileFineBookForm/index.tsx
src/m-pages/MobileCalendar/index.tsx
src/m-pages/MobileFineBookDetail/index.tsx
src/store/lockScrollState.ts

기존 useLockScroll은  trigger가 중첩으로 사용되었을 때 이슈가 있었습니다.
<br />
- useLockScroll 의 형태를 useLockScroll을 호출하는 곳에서 trigger 상태와 해당 Id 이름을 받아서 Set 자료구조에 삽입을 하고 해당 Set에 내용물이 존재할 경우만 스크롤을 고정해주는 형식으로 변경하였습니다.
<br />

Feat : useLockScroll 수정

---

src/components/Alarm/AlarmDetail/AlarmInfo/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/SingleCheckedFineList/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
src/pages/FineBook/DetailFine/index.tsx

<br />
- Style : 납부여부 및 요청 페이지 스타일 수정 
<br />
-

Style : 납부여부 및 요청 페이지 스타일 수정 

---

src/components/DetailFine/DropDownWrapper/CircleDropButton/index.tsx
src/components/DetailFine/DropDownWrapper/CircleDropButton/styles.ts
src/components/DetailFine/DropDownWrapper/index.tsx
src/components/DetailFine/FilterController/index.tsx
src/components/DetailFine/FilterController/styles.ts
src/components/DetailFine/TableHead/styles.ts
src/components/DetailFine/Toolbar/index.tsx
src/components/DetailFine/Toolbar/styles.ts
src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
src/m-components/MobileDetailFine/MobileDetailFineList/styles.ts
src/m-components/MobileDetailFine/index.tsx
src/pages/FineBook/DetailFine/styles.ts

<br />
- 상세내역 리스트 스타일 수정 (Sticky, 납부여부 변경 원형 버튼)
- Mobile 무한스크롤 에러 수정
- Mobile 날짜 sticky 추가
<br />
-

Feat: 상세내역 리스트 스타일 수정 / Mobile 무한스크롤 에러 수정 및 날짜 sticky

---

src/components/@common/Calendar/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/utils/sortNotificationInfo.ts
src/components/@common/Toast/index.tsx
src/components/@common/Toast/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/DropDownWrapper/CircleButtonList/index.tsx
src/components/DetailFine/DropDownWrapper/index.tsx
src/components/DetailFine/UserDetails/index.tsx
src/constants/Confirm.ts
src/hooks/Group/useNotificationForm.ts
src/layouts/Group/components/SideBar/index.tsx
src/m-components/BottomSheet/FilterBottomSheet/index.tsx
src/m-components/MobileMiniCalendar/index.tsx
src/queries/Group/useChangeNickname.ts
src/queries/Group/useGroupList.ts
src/queries/Group/useUpdateNotificationInfo.ts
src/queries/Group/useWithdrawalGroup.ts
src/styles/GlobalStyle.tsx

- 알림설정>매달>요일, 몇번째 항목 정렬
- 요일, 몇번째 실시간 변경 적용
- 모바일 설정할 수 없는 날짜 disabled
- 닉네임 바로 변경되지 않는 버그 수정
- 모달 문구 수정
<br />
-
<br />
-

Fix: QA리스트 수정

---

src/components/@common/MiniCalendar/styles.ts
src/components/@common/Modal/FineBookModal/FineBookCreateModal/index.tsx
src/layouts/Group/components/SideBar/index.tsx
src/layouts/Group/components/SideBar/styles.ts
src/m-components/BottomSheet/TimeBottomeSheet/index.tsx
src/m-pages/MobileCalendar/index.tsx

<br />
- [계속 추가하기 (연속클릭)이슈로 인한 Trigger 추가](https://github.com/so-sim/front/commit/72a70a8148a531b6047a9a4ba14d488b671232fd)
- [바텀시트 워딩 수정](https://github.com/so-sim/front/commit/8eb5dd354639323babe98bc3b8c4ca6029dd24b4)
-  미니캘린더 요일은 클릭 Style을 가지지않도록 오버라이딩
-  Mobile 설정한 시간이 Calendar에 노출되도록 수정
- [Mobile 사이드 버튼 disabled로 인한 클릭 이슈 수정](https://github.com/so-sim/front/commit/a0fe2b7b0bd8f704f477f5c4c454ebbbb9dcfc2c)
<br />
-

Feat: 스타일 수정 및 계속 추가하기 이슈 해결

---

src/components/@common/Calendar/index.tsx
src/components/@common/DropBox/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/MonthForm/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/NotifiactionForm/index.tsx
src/components/@common/Modal/GroupSettingModal/AdminModal/index.tsx
src/components/@common/Tooltip/index.tsx
src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/SituationButton/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/FilterController/AutoComplete/index.tsx
src/components/DetailFine/TableHead/index.tsx
src/components/DetailFine/Toolbar/index.tsx
src/components/DetailFine/UserDetails/index.tsx
src/constants/GA.ts
src/hooks/Group/useNotificationForm.ts
src/layouts/Group/components/SideBar/index.tsx
src/m-components/MobileDetailFine/MobileFilterController/index.tsx
src/m-components/MobileDetailFine/index.tsx
src/m-pages/MobileCalendar/index.tsx
src/m-pages/MobileFineBookDetail/index.tsx
src/queries/Group/useUpdateNotificationInfo.ts
src/queries/Notification/useRequestNotifaction.ts
src/store/requestNotificationState.ts

- 실시간 변경되는 notification 문구 수정 e44313643fedb277fc6db6b7935620d24440ab6c
- 납부요청 전송 시, 납부요청 버튼 비활성화 (추후 24시간으로 변경 예정)
- 툴팁 한 번만 나오도록 수정
- ga id 수정
<br />
-
<br />
-

Feat:qa 리스트 해결

---

src/components/@common/Calendar/DateCellWithMark/index.tsx
src/components/@common/Calendar/DateCellWithMark/styles.ts
src/components/@common/Calendar/DateCellWithTag/index.tsx
src/components/@common/Calendar/DateCellWithTag/styles.ts
src/components/@common/Checkbox/SelectAllCheckbox/index.tsx
src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/DetailList/styles.ts
src/components/DetailFine/DropDownWrapper/CircleButtonList/styles.ts
src/components/DetailFine/DropDownWrapper/CircleDropButton/styles.ts
src/components/DetailFine/TableHead/styles.ts
src/components/DetailFine/checkbox.tsx
src/m-components/MobileDetailFine/MobileToolbar/styles.ts
src/m-pages/MobileMemberManagement/index.tsx
src/m-pages/MobileMemberManagement/styles.ts
src/m-pages/MobileNotificationList/index.tsx
src/pages/MemberManagement/index.tsx
src/pages/MemberManagement/styles.ts

Fix: 디자인 QA 수정 및 Mobile 납부여부 페이지 에러 임시 수정

---

src/components/@common/Modal/UserConfigModal/styles.ts
src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/DropDownWrapper/index.tsx
src/components/DetailFine/FilterController/styles.ts
src/components/Home/Header/UserConfig/style.ts
src/constants/ServiceLink.ts
src/layouts/Group/components/GroupList/index.tsx
src/layouts/Group/components/SideBar/index.tsx
src/layouts/Mobile/components/MobileHeader/index.tsx
src/m-components/MobileDetailFine/MobileDetailFineList/index.tsx
src/m-components/MobileFineBookForm/index.tsx
src/m-pages/MobileFineBookDetail/index.tsx
src/m-pages/MobileHome/index.tsx
src/m-pages/MobileTOS/index.tsx
src/m-pages/MobileTOS/styles.ts
src/m-pages/MobileUserSetting/styles.ts
src/queries/Group/useGroupDetail.ts

Feat: qa 리스트 반영

---

src/components/@common/Modal/GroupSettingModal/UserModal/index.tsx
src/components/@common/Modal/styles.ts
src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/styles.ts
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/styles.ts
src/components/DetailFine/UserDetails/index.tsx
src/hooks/Group/useGroupForm.ts
src/m-pages/MobileSetting/MobileUserGroupSetting.tsx
src/pages/FineBook/DetailFine/styles.ts
src/store/checkListState.ts
src/store/sideModalState.ts

<br />
- 상세리스트자체가 스크롤 되도록 수정
- Mobile 일괄 납부여부 변경/요청 페이지 새로고침 대응
- 알람에서 납부여부 변경 시 Modal 추가
- 탈퇴한 회원의 이력이 있는 nickname 수정이 안되도록 수정
- 일괄 납부여부 변경/요청 페이지 Mount시 자세히보기 페이지 닫히도록 수정
<br />
-

Fix: QA 디자인 및 기능 수정

---

src/components/Alarm/AlarmDetail/AlarmInfo/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/DetailFine/AlarmRequest_PaymentUpdate/index.tsx
src/constants/GA_ALARM.ts
src/store/alarmInfoState.ts

<br />
-  알람 및 (Checkbox)납부여부 변경/요청 페이지 pushDataLayer 적용
<br />
-

Feat: 알람 및 (Checkbox)납부여부 변경/요청 페이지 pushDataLayer 적용

---

src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/UserDetails/index.tsx

<br />
- 단일 납부요청 datalayer 적용
<br />
-

feat: 단일 납부요청 datalayer 적용

---

src/m-pages/MobileFineBookDetail/index.tsx
src/m-pages/MobileFineBookDetail/styles.ts

<br />
- feat: Mobile 자세히보기 탈퇴뱃지 추가
<br />
-

feat: Mobile 자세히보기 탈퇴뱃지 추가

---

src/m-pages/MobileUserSetting/styles.ts

<br />
- design: Mobile setting 디자인 수정
<br />
-

design: Mobile setting 디자인 수정

---

src/api/Group/index.ts
src/constants/Confirm.ts
src/pages/Invitation/index.tsx
src/queries/Group/useGetInvitation.ts
src/queries/Group/useRejoinGroup.ts
src/types/group.d.ts

- 탈퇴한 유저가 해당 모임에 재가입했을 때 플로우 추가했습니다.
<br />
-
<br />
-

feat: 탈퇴한 모임에 재가입하는 유저 플로우 추가

---

src/components/DetailFine/DateController/FilterButton/styles.ts
src/components/DetailFine/DetailList/index.tsx
src/components/DetailFine/DetailList/styles.ts
src/m-components/MobileDetailFine/MobileToolbar/checkbox.tsx
src/m-components/MobileDetailFine/MobileToolbar/index.tsx
src/m-components/MobileDetailFine/MobileToolbar/styles.ts

Fix:디자인 QA

---

src/api/index.ts
src/components/@common/Tooltip/Situation/index.tsx
src/components/@common/Tooltip/Situation/styles.ts
src/hooks/Calendar/useCalendarState.ts
src/layouts/Group/components/GroupList/index.tsx
src/layouts/Mobile/MobileLayout.tsx
src/layouts/Mobile/components/MobileHeader/index.tsx
src/layouts/Mobile/components/MobileHeader/styles.ts
src/m-pages/MobileCalendar/index.tsx
src/utils/acceessToken.ts

- 리프레시 토큰 분기처리
- 스타일 qa 리스트 수정
<br />
-
<br />
- 00f29992b070cc73dad88ddf2339d0847a1672f9 
- 이부분 동작이 이해가 안 가서 한 번 이야기 나눠보고 싶습니다..!! @jma1020

fix: 리프레시 토큰 분기처리 및 스타일 수정

---

src/components/@common/Calendar/index.tsx
src/components/@common/Calendar/styles.ts

fix: 캘린더 min-width 추가

---

src/components/Alarm/AlarmDetail/AlarmList/AlarmCard/index.tsx
src/components/Alarm/AlarmDetail/AlarmList/index.tsx
src/constants/GA.ts

Release v2.1

---

src/App.tsx
src/Auth.tsx
src/queries/Auth/useReTakeToken.ts

<br />
- refetchinterval로  polling query 생성
- 해당 polling query 를 사용하는 AuthProvider 생성
- react query 디폴트 옵션 수정
<br />
-

Feat: access 재발급 api polling 적용

---

src/App.tsx
src/hooks/Shared/Errorboundary.tsx

feat: class 에러 바운더리
